version: '3.8'

services:
  n8n:
    # Option 1: Utiliser l'image hébergée (recommandé)
    image: ghcr.io/archlord12345/kernel_docker/n8n-kernel:latest
    # Option 2: Build local (décommentez la ligne suivante et commentez image:)
    # build: .
    container_name: n8n-kernel
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Paris
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  n8n_data:
    driver: local

networks:
  n8n-network:
    driver: bridge
