services:
  - type: web
    name: n8n-kernel
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: WEBHOOK_URL
        value: https://n8n-kernel.onrender.com/
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
